// Generated by CoffeeScript 1.12.2
(function() {
  var app, bodyParser, cookieParser, exec, express, favicon, fs, logger, path, routes;

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  global.appRoot = path.resolve(__dirname);

  routes = require('./routes/index');

  fs = require('fs');

  exec = require('child_process').exec;

  fs.lstat(global.appRoot + '/public/node_modules', function(err, stats) {
    var cmd;
    if (err) {
      cmd = "ln -s " + global.appRoot + "/node_modules public/node_modules";
      return exec(cmd, function(err, stdout, stdin) {
        console.log(stdout);
        return console.log('create simlink');
      });
    }
  });

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cookieParser());

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use('/', routes);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);
