// Generated by CoffeeScript 1.11.1
(function() {
  var app, connect, http;

  connect = require('connect');

  http = require('http');

  app = connect();

  app.use(function(req, res, next) {
    console.log('one');
    return next();
  }).use(function(req, res, next) {
    console.log('two');
    return next();
  }).use(function(req, res, next) {
    res.write(JSON.stringify({
      x: 10,
      y: 40
    }));
    return res.end();
  });

  http.createServer(app).listen(8080);

}).call(this);
