// Generated by CoffeeScript 1.11.1
(function() {
  var is_auth;

  is_auth = function(pars) {
    var query;
    query = function(req, res, next) {
      console.log('Authentication');
      console.log(pars);
      console.log(req.session);
      return next();
    };
    return query;
  };

  module.exports = is_auth;

}).call(this);
