// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = function(io) {
    var sockets;
    sockets = {};
    return io.on('connection', function(client) {
      console.log('Client connected...');
      client.on('join', function(data) {
        sockets[data.user_id] = client;
        return io.emit('someone_joined', {
          user_id: data.user_id,
          act: 'someone_joined'
        });
      });
      return client.on('disconnection', function(data) {
        delete sockets[data.user_id];
        return io.emit('someone_left', {
          user_id: data.user_id,
          act: 'someone_left'
        });
      });
    });
  };


  /*
      setInterval ()->
          time = new Date()
          io.emit('time', {time: time});
          console.log "just have sent #{time}"
      ,5000
   */

}).call(this);
