// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = function(io) {
    var sockets, users_online;
    sockets = {};
    users_online = [];
    return io.on('connection', function(client) {
      console.log('Client connected...');
      client.on('join', function(data) {
        sockets[data.user_id] = client;
        users_online.push(data.user_id);
        return io.emit('someone_joined', {
          user_id: data.user_id,
          act: 'someone_joined',
          users_online: users_online
        });
      });
      client.on('disconnection', function(data) {
        var index;
        delete sockets[data.user_id];
        index = users_online.indexOf(data.user_id);
        if (index !== -1) {
          users_online.splice(index, 1);
        }
        return io.emit('someone_left', {
          user_id: data.user_id,
          act: 'someone_left',
          users_online: users_online
        });
      });
      return client.on('send_message', function(data) {
        console.log(data);
        return sockets[data.to_user_id].emit('take_message', {
          message: data.message
        });
      });
    });
  };

}).call(this);
