// Generated by CoffeeScript 1.11.1
(function() {
  module.exports = function(io) {
    var sockets;
    sockets = {};
    return io.on('connection', function(client) {
      console.log('Client connected...');
      client.on('join', function(data) {
        sockets[data.user_id] = '';
        return console.log(sockets);
      });
      return client.on('disconnect', function(data) {
        delete sockets[data.user_id];
        return console.log('ssssssssssssssssssssss');
      });
    });
  };


  /*
      setInterval ()->
          time = new Date()
          io.emit('time', {time: time});
          console.log "just have sent #{time}"
      ,5000
   */

}).call(this);
