// Generated by CoffeeScript 1.11.1
(function() {
  var Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  module.exports = mongoose.model('User', new Schema({
    name: String,
    password: String,
    admin: Boolean
  }));

}).call(this);
