// Generated by CoffeeScript 1.11.1
(function() {
  var add, i, showdt;

  add = function(a, b) {
    return a + b;
  };

  add = function(a, b, callback) {
    return setTimeout(function() {
      return callback(a + b);
    }, 10);
  };

  console.log('before');

  add(1, 2, function(res) {
    return console.log('result ' + res);
  });

  console.log('after');

  i = 0;

  showdt = function() {
    i = i + 1;
    console.log(i);
    return process.nextTick(showdt);
  };

  showdt();

}).call(this);
