// Generated by CoffeeScript 1.11.1
(function() {
  var i, j, sum;

  sum = 0;

  for (i = j = 1; j <= 10; i = ++j) {
    sum = sum + i;
    console.log("iteration " + i);
    debugger;
  }

}).call(this);
