// Generated by CoffeeScript 1.11.1
(function() {
  'use strict';
  var http, myf, server, url;

  http = require('http');

  url = require('url');

  server = http.createServer(function(req, res) {
    var ex, path;
    try {
      path = url.parse(req.url).pathname;
      res.end("hello from " + path);
      myf();
      return console.log("got request");
    } catch (error) {
      ex = error;
      return res.end("Error " + ex);
    }
  });

  myf = function() {
    console.log('one');
    console.log('two');
    return console.log('three');
  };

  server.listen(8088);

  console.log('Server running on 8080');

}).call(this);
