// Generated by CoffeeScript 1.11.1
(function() {
  var client, connectionString, express, pg, query, router;

  express = require('express');

  router = express.Router();

  pg = require('pg');

  connectionString = process.env.DATABASE_URL || 'postgres://postgres:1q2w3e@localhost:5432/todo';

  client = new pg.Client(connectionString);

  client.connect();

  query = client.query('CREATE TABLE IF NOT EXISTS pages(id SERIAL PRIMARY KEY, title VARCHAR(40) not null, text TEXT, published BOOLEAN)');

  router.get('/list', function(req, res, next) {
    var results;
    results = [];
    query = client.query('SELECT * FROM pages ORDER BY id ASC;');
    query.on('row', function(row) {
      return results.push(row);
    });
    return query.on('end', function() {
      return res.send(results);
    });
  });

  router.post('/save', function(req, res, next) {
    var page;
    page = req.body;
    if (page.is_new) {
      client.query('INSERT INTO pages(title,text) values($1, $2)', page.title, page.text);
    } else {
      client.query('UPDATE items SET text=($1), complete=($2) WHERE id=($3)', page.title, page.text, page.id);
    }
    return res.send('ok');
  });

  router.get('/detail/:id', function(req, res, next) {
    query = client.query('SELECT * FROM pages WHERE id=($1);', [req.params.id]);
    return query.on('row', function(row) {
      return res.send(row);
    });
  });

  router.get('/delete/:id', function(req, res, next) {
    query = client.query('DELETE FROM pages WHERE id=($1);', [req.params.id]);
    return query.on('end', function(row) {
      return res.send('ok');
    });
  });

  module.exports = router;

}).call(this);
