// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, fs, path, port;

  express = require('express');

  fs = require('fs');

  path = require('path');

  app = express();

  port = process.env.PORT || 5555;

  app.get('/', function(req, res) {
    return fs.readFile('index.html', 'utf8', function(err, data) {
      if (err) {
        return console.log('I can not find index.html');
      } else {
        return res.send(data);
      }
    });
  });

  app.get('/contacts', function(req, res) {
    return res.send([
      {
        'id': 1,
        'name': 'Piter',
        'phone': '342534'
      }, {
        'id': 2,
        'name': 'John',
        'phone': '842534'
      }, {
        'id': 3,
        'name': 'Mike',
        'phone': '642534'
      }
    ]);
  });

  app.use(express["static"](__dirname));

  app.listen(port);

  console.log('I am going on ' + port);

}).call(this);
