// Generated by CoffeeScript 1.10.0
(function() {
  var fs, http, mimeTypes, pathutil, server, url;

  http = require('http');

  fs = require('fs');

  url = require('url');

  pathutil = require('path');

  mimeTypes = {
    '.js': 'text/javascript',
    '.css': 'text/css',
    '.html': 'text/html'
  };

  server = http.createServer(function(req, res) {
    var ext, mime, path;
    path = url.parse(req.url).pathname;
    if (path === '/') {
      path = '/routing.html';
    }
    ext = pathutil.extname(path);
    mime = mimeTypes[ext];
    path = path.substring(1, path.lenght);
    console.log(path);
    return fs.readFile(path, 'utf8', function(err, data) {
      if (err) {
        return console.log('I can not find ' + path);
      } else {
        res.writeHead(200, {
          'Content-Type': mime
        });
        return res.end(data);
      }
    });
  });

  server.listen(8080);

  console.log('Server running on 8080');

}).call(this);
