// Generated by CoffeeScript 1.10.0
(function() {
  var app, connect, http;

  connect = require('connect');

  http = require('http');

  app = connect().use(function(req, res, next) {
    console.log('First middleware');
    res.name = 'Dima';
    return next();
  }).use(function(req, res, next) {
    console.log("Second middleware " + res.name);
    return next();
  }).use(function(req, res, next) {
    console.log('end');
    return res.end('hello world');
  });

  http.createServer(app).listen(3333);

}).call(this);
