// Generated by CoffeeScript 1.10.0
(function() {
  exports.setup = function(app) {
    return app.get('/contact', function(req, res) {
      return res.send('Contact!!');
    });
  };

}).call(this);
