// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('articleApp', ['ngRoute']).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'list.html',
      controller: 'testCtrl'
    });
  }).controller('testCtrl', [
    '$scope', function($scope) {
      $scope.message = 'Hello World!!!';
      return $scope.items = [
        {
          'name': 'Dima'
        }, {
          'name': 'Vova'
        }
      ];
    }
  ]);

}).call(this);
